In [ ]:
import matplotlib.pyplot as plt
import numpy as np
import os
import tensorflow as tf
from tensorflow.keras.preprocessing import image_dataset_from_directory
from tensorflow.keras.preprocessing import image
import numpy as np 
import pandas as pd
from os import listdir
from PIL import Image as PImagea
from skimage.transform import resize
from random import shuffle
import cv2
import sklearn
import numpy as np
import matplotlib as mpl
import matplotlib.pyplot as plt
import math
import glob
import tensorflow as tf
from keras.models import Sequential
from keras.models import Model
from keras.callbacks import ModelCheckpoint, LearningRateScheduler, EarlyStopping, ReduceLROnPlateau, TensorBoard
from keras import optimizers, losses, activations, models
from keras.layers import Convolution2D, Dense, Input, Flatten, Dropout, MaxPooling2D, BatchNormalization, GlobalAveragePooling2D, Concatenate
from keras import applications
from keras.applications.inception_v3 import preprocess_input
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from matplotlib.image import NonUniformImage
from google.colab.patches import cv2_imshow
from tensorflow.keras.applications.inception_v3 import InceptionV3
from tensorflow.keras.applications.inception_v3 import decode_predictions
from tensorflow.keras.layers import Input


In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
aluminium_foil = glob.glob('/content/drive/MyDrive/PS I G3/Dataset/KTH-TIPS 2-a/KTH-TIPS2-a/aluminium_foil/sample_a/*.*')
brown_bread = glob.glob('/content/drive/MyDrive/PS I G3/Dataset/KTH-TIPS 2-a/KTH-TIPS2-a/brown_bread/sample_a/*.*')
corduroy = glob.glob('/content/drive/MyDrive/PS I G3/Dataset/KTH-TIPS 2-a/KTH-TIPS2-a/corduroy/sample_a/*.*')
cork = glob.glob('/content/drive/MyDrive/PS I G3/Dataset/KTH-TIPS 2-a/KTH-TIPS2-a/cork/sample_a/*.*')
cotton = glob.glob('/content/drive/MyDrive/PS I G3/Dataset/KTH-TIPS 2-a/KTH-TIPS2-a/cotton/sample_a/*.*')
cracker = glob.glob('/content/drive/MyDrive/PS I G3/Dataset/KTH-TIPS 2-a/KTH-TIPS2-a/cracker/sample_a/*.*')
lettuce_leaf = glob.glob('/content/drive/MyDrive/PS I G3/Dataset/KTH-TIPS 2-a/KTH-TIPS2-a/lettuce_leaf/sample_a/*.*')
linen = glob.glob('/content/drive/MyDrive/PS I G3/Dataset/KTH-TIPS 2-a/KTH-TIPS2-a/linen/sample_a/*.*')
white_bread = glob.glob('/content/drive/MyDrive/PS I G3/Dataset/KTH-TIPS 2-a/KTH-TIPS2-a/white_bread/sample_a/*.*')
wood = glob.glob('/content/drive/MyDrive/PS I G3/Dataset/KTH-TIPS 2-a/KTH-TIPS2-a/wood/sample_a/*.*')
wool = glob.glob('/content/drive/MyDrive/PS I G3/Dataset/KTH-TIPS 2-a/KTH-TIPS2-a/wool/sample_a/*.*')



data = []
labels = []
j= 0
for i in aluminium_foil:
    # if j>100:
    #     break
    image=tf.keras.preprocessing.image.load_img(i, color_mode="rgb", target_size= (448,448))
    image=np.array(image)
    data.append(image)
    labels.append(0)
    j +=1
for i in brown_bread:
    # if j>200:
    #     break
    image=tf.keras.preprocessing.image.load_img(i, color_mode="rgb", target_size= (448,448))
    image=np.array(image)
    data.append(image)
    labels.append(1)
    j +=1
for i in corduroy:
    # if j>300:
    #     break
    image=tf.keras.preprocessing.image.load_img(i, color_mode="rgb", target_size= (448,448))
    image=np.array(image)
    data.append(image)
    labels.append(2)
    j +=1
for i in cork:
    # if j>400:
    #     break
    image=tf.keras.preprocessing.image.load_img(i, color_mode="rgb", target_size= (448,448))
    image=np.array(image)
    data.append(image)
    labels.append(3)
    j+=1
for i in cotton:
    # if j>500 :
    #     break
    image=tf.keras.preprocessing.image.load_img(i, color_mode="rgb", target_size= (448,448))
    image=np.array(image)
    data.append(image)
    labels.append(4)
    j+=1
for i in cracker:
    # if j> 600:
    #     break
    image=tf.keras.preprocessing.image.load_img(i, color_mode="rgb", target_size= (448,448))
    image=np.array(image)
    data.append(image)
    labels.append(5)
    j+=1
for i in lettuce_leaf:
    # if j> 700:
    #     break
    image=tf.keras.preprocessing.image.load_img(i, color_mode="rgb", target_size= (448,448))
    image=np.array(image)
    data.append(image)
    labels.append(6)
    j+=1
for i in linen:
    # if j> 800:
    #     break
    image=tf.keras.preprocessing.image.load_img(i, color_mode="rgb", target_size= (448,448))
    image=np.array(image)
    data.append(image)
    labels.append(7)
    j+=1
for i in white_bread:
    # if j> 900:
    #     break
    image=tf.keras.preprocessing.image.load_img(i, color_mode="rgb", target_size= (448,448))
    image=np.array(image)
    data.append(image)
    labels.append(8)
    j+=1
for i in wood:
    # if j> 1000:
    #     break
    image=tf.keras.preprocessing.image.load_img(i, color_mode="rgb", target_size= (448,448))
    image=np.array(image)
    data.append(image)
    labels.append(9)
    j+=1
for i in wool:
    # if j> 1100:
    #     break
    image=tf.keras.preprocessing.image.load_img(i, color_mode="rgb", target_size= (448,448))
    image=np.array(image)
    data.append(image)
    labels.append(10)
    j+=1
print('total images = ',j)
# data = np.array(data)
# labels = np.array(labels)

total images =  12


In [ ]:
aluminium_foil = glob.glob('/content/drive/MyDrive/PS I G3/Dataset/KTH-TIPS 2-a/KTH-TIPS2-a/aluminium_foil/sample_b/*.*')
brown_bread = glob.glob('/content/drive/MyDrive/PS I G3/Dataset/KTH-TIPS 2-a/KTH-TIPS2-a/brown_bread/sample_b/*.*')
corduroy = glob.glob('/content/drive/MyDrive/PS I G3/Dataset/KTH-TIPS 2-a/KTH-TIPS2-a/corduroy/sample_b/*.*')
cork = glob.glob('/content/drive/MyDrive/PS I G3/Dataset/KTH-TIPS 2-a/KTH-TIPS2-a/cork/sample_b/*.*')
cotton = glob.glob('/content/drive/MyDrive/PS I G3/Dataset/KTH-TIPS 2-a/KTH-TIPS2-a/cotton/sample_b/*.*')
cracker = glob.glob('/content/drive/MyDrive/PS I G3/Dataset/KTH-TIPS 2-a/KTH-TIPS2-a/cracker/sample_b/*.*')
lettuce_leaf = glob.glob('/content/drive/MyDrive/PS I G3/Dataset/KTH-TIPS 2-a/KTH-TIPS2-a/lettuce_leaf/sample_b/*.*')
linen = glob.glob('/content/drive/MyDrive/PS I G3/Dataset/KTH-TIPS 2-a/KTH-TIPS2-a/linen/sample_b/*.*')
white_bread = glob.glob('/content/drive/MyDrive/PS I G3/Dataset/KTH-TIPS 2-a/KTH-TIPS2-a/white_bread/sample_b/*.*')
wood = glob.glob('/content/drive/MyDrive/PS I G3/Dataset/KTH-TIPS 2-a/KTH-TIPS2-a/wood/sample_b/*.*')
wool = glob.glob('/content/drive/MyDrive/PS I G3/Dataset/KTH-TIPS 2-a/KTH-TIPS2-a/wool/sample_b/*.*')




# data = []
# labels = []
# j= 0
for i in aluminium_foil:
    # if j>100:
    #     break
    image=tf.keras.preprocessing.image.load_img(i, color_mode="rgb", target_size= (448,448))
    image=np.array(image)
    data.append(image)
    labels.append(0)
    j +=1
for i in brown_bread:
    # if j>200:
    #     break
    image=tf.keras.preprocessing.image.load_img(i, color_mode="rgb", target_size= (448,448))
    image=np.array(image)
    data.append(image)
    labels.append(1)
    j +=1
for i in corduroy:
    # if j>300:
    #     break
    image=tf.keras.preprocessing.image.load_img(i, color_mode="rgb", target_size= (448,448))
    image=np.array(image)
    data.append(image)
    labels.append(2)
    j +=1
for i in cork:
    # if j>400:
    #     break
    image=tf.keras.preprocessing.image.load_img(i, color_mode="rgb", target_size= (448,448))
    image=np.array(image)
    data.append(image)
    labels.append(3)
    j+=1
for i in cotton:
    # if j>500 :
    #     break
    image=tf.keras.preprocessing.image.load_img(i, color_mode="rgb", target_size= (448,448))
    image=np.array(image)
    data.append(image)
    labels.append(4)
    j+=1
for i in cracker:
    # if j> 600:
    #     break
    image=tf.keras.preprocessing.image.load_img(i, color_mode="rgb", target_size= (448,448))
    image=np.array(image)
    data.append(image)
    labels.append(5)
    j+=1
for i in lettuce_leaf:
    # if j> 700:
    #     break
    image=tf.keras.preprocessing.image.load_img(i, color_mode="rgb", target_size= (448,448))
    image=np.array(image)
    data.append(image)
    labels.append(6)
    j+=1
for i in linen:
    # if j> 800:
    #     break
    image=tf.keras.preprocessing.image.load_img(i, color_mode="rgb", target_size= (448,448))
    image=np.array(image)
    data.append(image)
    labels.append(7)
    j+=1
for i in white_bread:
    # if j> 900:
    #     break
    image=tf.keras.preprocessing.image.load_img(i, color_mode="rgb", target_size= (448,448))
    image=np.array(image)
    data.append(image)
    labels.append(8)
    j+=1
for i in wood:
    # if j> 1000:
    #     break
    image=tf.keras.preprocessing.image.load_img(i, color_mode="rgb", target_size= (448,448))
    image=np.array(image)
    data.append(image)
    labels.append(9)
    j+=1
for i in wool:
    # if j> 1100:
    #     break
    image=tf.keras.preprocessing.image.load_img(i, color_mode="rgb", target_size= (448,448))
    image=np.array(image)
    data.append(image)
    labels.append(10)
    j+=1
print('total test images = ',j)
# data = np.array(data)
# labels = np.array(labels)

total test images =  2376


In [ ]:
aluminium_foil = glob.glob('/content/drive/MyDrive/PS I G3/Dataset/KTH-TIPS 2-a/KTH-TIPS2-a/aluminium_foil/sample_c/*.*')
brown_bread = glob.glob('/content/drive/MyDrive/PS I G3/Dataset/KTH-TIPS 2-a/KTH-TIPS2-a/brown_bread/sample_c/*.*')
corduroy = glob.glob('/content/drive/MyDrive/PS I G3/Dataset/KTH-TIPS 2-a/KTH-TIPS2-a/corduroy/sample_c/*.*')
cork = glob.glob('/content/drive/MyDrive/PS I G3/Dataset/KTH-TIPS 2-a/KTH-TIPS2-a/cork/sample_c/*.*')
cotton = glob.glob('/content/drive/MyDrive/PS I G3/Dataset/KTH-TIPS 2-a/KTH-TIPS2-a/cotton/sample_c/*.*')
cracker = glob.glob('/content/drive/MyDrive/PS I G3/Dataset/KTH-TIPS 2-a/KTH-TIPS2-a/cracker/sample_c/*.*')
lettuce_leaf = glob.glob('/content/drive/MyDrive/PS I G3/Dataset/KTH-TIPS 2-a/KTH-TIPS2-a/lettuce_leaf/sample_c/*.*')
linen = glob.glob('/content/drive/MyDrive/PS I G3/Dataset/KTH-TIPS 2-a/KTH-TIPS2-a/linen/sample_c/*.*')
white_bread = glob.glob('/content/drive/MyDrive/PS I G3/Dataset/KTH-TIPS 2-a/KTH-TIPS2-a/white_bread/sample_c/*.*')
wood = glob.glob('/content/drive/MyDrive/PS I G3/Dataset/KTH-TIPS 2-a/KTH-TIPS2-a/wood/sample_c/*.*')
wool = glob.glob('/content/drive/MyDrive/PS I G3/Dataset/KTH-TIPS 2-a/KTH-TIPS2-a/wool/sample_c/*.*')





for i in aluminium_foil:
    # if j>100:
    #     break
    image=tf.keras.preprocessing.image.load_img(i, color_mode="rgb", target_size= (448,448))
    image=np.array(image)
    data.append(image)
    labels.append(0)
    j +=1
for i in brown_bread:
    # if j>200:
    #     break
    image=tf.keras.preprocessing.image.load_img(i, color_mode="rgb", target_size= (448,448))
    image=np.array(image)
    data.append(image)
    labels.append(1)
    j +=1
for i in corduroy:
    # if j>300:
    #     break
    image=tf.keras.preprocessing.image.load_img(i, color_mode="rgb", target_size= (448,448))
    image=np.array(image)
    data.append(image)
    labels.append(2)
    j +=1
for i in cork:
    # if j>400:
    #     break
    image=tf.keras.preprocessing.image.load_img(i, color_mode="rgb", target_size= (448,448))
    image=np.array(image)
    data.append(image)
    labels.append(3)
    j+=1
for i in cotton:
    # if j>500 :
    #     break
    image=tf.keras.preprocessing.image.load_img(i, color_mode="rgb", target_size= (448,448))
    image=np.array(image)
    data.append(image)
    labels.append(4)
    j+=1
for i in cracker:
    # if j> 600:
    #     break
    image=tf.keras.preprocessing.image.load_img(i, color_mode="rgb", target_size= (448,448))
    image=np.array(image)
    data.append(image)
    labels.append(5)
    j+=1
for i in lettuce_leaf:
    # if j> 700:
    #     break
    image=tf.keras.preprocessing.image.load_img(i, color_mode="rgb", target_size= (448,448))
    image=np.array(image)
    data.append(image)
    labels.append(6)
    j+=1
for i in linen:
    # if j> 800:
    #     break
    image=tf.keras.preprocessing.image.load_img(i, color_mode="rgb", target_size= (448,448))
    image=np.array(image)
    data.append(image)
    labels.append(7)
    j+=1
for i in white_bread:
    # if j> 900:
    #     break
    image=tf.keras.preprocessing.image.load_img(i, color_mode="rgb", target_size= (448,448))
    image=np.array(image)
    data.append(image)
    labels.append(8)
    j+=1
for i in wood:
    # if j> 1000:
    #     break
    image=tf.keras.preprocessing.image.load_img(i, color_mode="rgb", target_size= (448,448))
    image=np.array(image)
    data.append(image)
    labels.append(9)
    j+=1
for i in wool:
    # if j> 1100:
    #     break
    image=tf.keras.preprocessing.image.load_img(i, color_mode="rgb", target_size= (448,448))
    image=np.array(image)
    data.append(image)
    labels.append(10)
    j+=1
print('total images = ',j)
# data = np.array(data)
# labels = np.array(labels)

total images =  3564


In [ ]:
aluminium_foil = glob.glob('/content/drive/MyDrive/PS I G3/Dataset/KTH-TIPS 2-a/KTH-TIPS2-a/aluminium_foil/sample_d/*.*')
brown_bread = glob.glob('/content/drive/MyDrive/PS I G3/Dataset/KTH-TIPS 2-a/KTH-TIPS2-a/brown_bread/sample_d/*.*')
corduroy = glob.glob('/content/drive/MyDrive/PS I G3/Dataset/KTH-TIPS 2-a/KTH-TIPS2-a/corduroy/sample_d/*.*')
cork = glob.glob('/content/drive/MyDrive/PS I G3/Dataset/KTH-TIPS 2-a/KTH-TIPS2-a/cork/sample_d/*.*')
cotton = glob.glob('/content/drive/MyDrive/PS I G3/Dataset/KTH-TIPS 2-a/KTH-TIPS2-a/cotton/sample_d/*.*')
cracker = glob.glob('/content/drive/MyDrive/PS I G3/Dataset/KTH-TIPS 2-a/KTH-TIPS2-a/cracker/sample_d/*.*')
lettuce_leaf = glob.glob('/content/drive/MyDrive/PS I G3/Dataset/KTH-TIPS 2-a/KTH-TIPS2-a/lettuce_leaf/sample_d/*.*')
linen = glob.glob('/content/drive/MyDrive/PS I G3/Dataset/KTH-TIPS 2-a/KTH-TIPS2-a/linen/sample_d/*.*')
white_bread = glob.glob('/content/drive/MyDrive/PS I G3/Dataset/KTH-TIPS 2-a/KTH-TIPS2-a/white_bread/sample_d/*.*')
wood = glob.glob('/content/drive/MyDrive/PS I G3/Dataset/KTH-TIPS 2-a/KTH-TIPS2-a/wood/sample_d/*.*')
wool = glob.glob('/content/drive/MyDrive/PS I G3/Dataset/KTH-TIPS 2-a/KTH-TIPS2-a/wool/sample_d/*.*')




for i in aluminium_foil:
    # if j>100:
    #     break
    image=tf.keras.preprocessing.image.load_img(i, color_mode="rgb", target_size= (448,448))
    image=np.array(image)
    data.append(image)
    labels.append(0)
    j +=1
for i in brown_bread:
    # if j>200:
    #     break
    image=tf.keras.preprocessing.image.load_img(i, color_mode="rgb", target_size= (448,448))
    image=np.array(image)
    data.append(image)
    labels.append(1)
    j +=1
for i in corduroy:
    # if j>300:
    #     break
    image=tf.keras.preprocessing.image.load_img(i, color_mode="rgb", target_size= (448,448))
    image=np.array(image)
    data.append(image)
    labels.append(2)
    j +=1
for i in cork:
    # if j>400:
    #     break
    image=tf.keras.preprocessing.image.load_img(i, color_mode="rgb", target_size= (448,448))
    image=np.array(image)
    data.append(image)
    labels.append(3)
    j+=1
for i in cotton:
    # if j>500 :
    #     break
    image=tf.keras.preprocessing.image.load_img(i, color_mode="rgb", target_size= (448,448))
    image=np.array(image)
    data.append(image)
    labels.append(4)
    j+=1
for i in cracker:
    # if j> 600:
    #     break
    image=tf.keras.preprocessing.image.load_img(i, color_mode="rgb", target_size= (448,448))
    image=np.array(image)
    data.append(image)
    labels.append(5)
    j+=1
for i in lettuce_leaf:
    # if j> 700:
    #     break
    image=tf.keras.preprocessing.image.load_img(i, color_mode="rgb", target_size= (448,448))
    image=np.array(image)
    data.append(image)
    labels.append(6)
    j+=1
for i in linen:
    # if j> 800:
    #     break
    image=tf.keras.preprocessing.image.load_img(i, color_mode="rgb", target_size= (448,448))
    image=np.array(image)
    data.append(image)
    labels.append(7)
    j+=1
for i in white_bread:
    # if j> 900:
    #     break
    image=tf.keras.preprocessing.image.load_img(i, color_mode="rgb", target_size= (448,448))
    image=np.array(image)
    data.append(image)
    labels.append(8)
    j+=1
for i in wood:
    # if j> 1000:
    #     break
    image=tf.keras.preprocessing.image.load_img(i, color_mode="rgb", target_size= (448,448))
    image=np.array(image)
    data.append(image)
    labels.append(9)
    j+=1
for i in wool:
    # if j> 1100:
    #     break
    image=tf.keras.preprocessing.image.load_img(i, color_mode="rgb", target_size= (448,448))
    image=np.array(image)
    data.append(image)
    labels.append(10)
    j+=1
print('total images = ',j)
data = np.array(data)
labels = np.array(labels)

total images =  4608


In [ ]:
X_train, X_test, y_train, y_test = train_test_split(data, labels, test_size=0.2, random_state=42)

In [ ]:
# X_train, X_test, y_train, y_test = data, X_test,labels,y_test

In [ ]:
rows,cols,channels = np.shape(data[0])
print('rows,cols,channels = ',rows,cols,channels)

rows,cols,channels =  448 448 3


In [ ]:
X_train.shape

(9, 448, 448, 3)

In [ ]:
# model_pretrained = tf.keras.applications.InceptionV3(weights="imagenet",include_top=False,input_shape=(rows,cols,3))
# model_pretrained.summary()

# inp = model_pretrained.input
# out = model_pretrained.layers[-2].output

from tensorflow.keras.applications.vgg16 import VGG16
from tensorflow.keras.applications.vgg16 import preprocess_input
import numpy as np
from tensorflow.keras.preprocessing import image
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Dense, GlobalAveragePooling2D
import tensorflow as tf

# create the base pre-trained model
model_pretrained = VGG16(weights='imagenet', include_top=False,input_shape=(rows,cols,3))
model_pretrained.summary()

# first: train only the top layers (which were randomly initialized)
# i.e. freeze all convolutional InceptionV3 layers except the last dense 
# layer for 11 classes that was just added.
for layer in model_pretrained.layers[:-1]:
    layer.trainable = False
# for layer in model_pretrained.layers[15:]:
#     layer.trainable = True
numClasses=11

x = model_pretrained.get_layer(index=-2).output
x_5 = model_pretrained.get_layer(index=-5).output
added_layer = tf.einsum('ijkm,ijkn->imn',x,x_5)
x = tf.reshape(added_layer,[-1,512*512])
print('Shape of phi_I after reshape', x.get_shape())

x = tf.divide(x,(784.0))  
print('Shape of phi_I after division', x.get_shape())

a = tf.multiply(tf.sign(x),tf.sqrt(tf.abs(x)+1e-12))
print('Shape of y_ssqrt', a.get_shape())

z = tf.nn.l2_normalize(a, dim=1)
print('Shape of z_l2', z.get_shape())

# and a logistic layer -- let's say we have 24 classes
predictions = Dense(numClasses, activation='softmax')(z)

# this is the model we will train
model = Model(inputs=model_pretrained.input, outputs=predictions)

# compile the model (should be done *after* setting layers to non-trainable)
model.compile(optimizer='rmsprop', loss='categorical_crossentropy',metrics=['accuracy'])
# y_train = np.asarray(y_train).astype('float32').reshape((-1,1))
# y_test = np.asarray(y_test).astype('float32').reshape((-1,1))
one_hot_labels = tf.keras.utils.to_categorical(labels, num_classes=numClasses)
model.summary()
model.fit(x=data,y=one_hot_labels,epochs=10,batch_size=32)



58892288/58889256 [==============================] - 1s 0us/step
Model: "vgg16"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_1 (InputLayer)         [(None, 448, 448, 3)]     0         
_________________________________________________________________
block1_conv1 (Conv2D)        (None, 448, 448, 64)      1792      
_________________________________________________________________
block1_conv2 (Conv2D)        (None, 448, 448, 64)      36928     
_________________________________________________________________
block1_pool (MaxPooling2D)   (None, 224, 224, 64)      0         
_________________________________________________________________
block2_conv1 (Conv2D)        (None, 224, 224, 128)     73856     
_________________________________________________________________
block2_conv2 (Conv2D)        (None, 224, 224, 128)     147584    
______________________________________________________________

m+d w/o ft

In [ ]:
one_hot_labels_test = tf.keras.utils.to_categorical(y_test, num_classes=11)
test_loss,test_acc = model.evaluate(X_test,  one_hot_labels_test, verbose=2)

print('\nTest accuracy:', test_acc*100,"%")

29/29 - 15s - loss: 0.0140 - accuracy: 0.9978

Test accuracy: 99.78308081626892 %


In [ ]:
# model_pretrained = tf.keras.applications.InceptionV3(weights="imagenet",include_top=False,input_shape=(rows,cols,3))
# model_pretrained.summary()

# inp = model_pretrained.input
# out = model_pretrained.layers[-2].output

from tensorflow.keras.applications.vgg16 import VGG16
from tensorflow.keras.applications.vgg16 import preprocess_input
import numpy as np
from tensorflow.keras.preprocessing import image
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Dense, GlobalAveragePooling2D
import tensorflow as tf

# create the base pre-trained model
model_pretrained = VGG16(weights='imagenet', include_top=False,input_shape=(rows,cols,3))
model_pretrained.summary()

# first: train only the top layers (which were randomly initialized)
# i.e. freeze all convolutional InceptionV3 layers except the last dense 
# layer for 11 classes that was just added.
for layer in model_pretrained.layers[:-1]:
    layer.trainable = False
# for layer in model_pretrained.layers[15:]:
#     layer.trainable = True
numClasses=11

x = model_pretrained.get_layer(index=-2).output
x_5 = model_pretrained.get_layer(index=-5).output
added_layer = tf.einsum('ijkm,ijkn->imn',x,x)
x = tf.reshape(added_layer,[-1,512*512])
print('Shape of phi_I after reshape', x.get_shape())

x = tf.divide(x,(784.0))  
print('Shape of phi_I after division', x.get_shape())

a = tf.multiply(tf.sign(x),tf.sqrt(tf.abs(x)+1e-12))
print('Shape of y_ssqrt', a.get_shape())

z = tf.nn.l2_normalize(a, dim=1)
print('Shape of z_l2', z.get_shape())


# x = GlobalAveragePooling2D()(x)
# let's add a fully-connected layer
# x = Dense(1024, activation='relu')(x)
# x = Dense(1024, activation='relu')(x)

# and a logistic layer -- let's say we have 24 classes
predictions = Dense(numClasses, activation='softmax')(z)



# this is the model we will train
model = tf.keras.Model(inputs=model_pretrained.input, outputs=predictions)

# compile the model (should be done *after* setting layers to non-trainable)
model.compile(optimizer='rmsprop', loss='categorical_crossentropy',metrics=['accuracy'])
# y_train = np.asarray(y_train).astype('float32').reshape((-1,1))
# y_test = np.asarray(y_test).astype('float32').reshape((-1,1))
one_hot_labels = tf.keras.utils.to_categorical(labels, num_classes=numClasses)
model.summary()
model.fit(x=data,y=one_hot_labels,epochs=10,batch_size=32)


Model: "vgg16"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_9 (InputLayer)         [(None, 448, 448, 3)]     0         
_________________________________________________________________
block1_conv1 (Conv2D)        (None, 448, 448, 64)      1792      
_________________________________________________________________
block1_conv2 (Conv2D)        (None, 448, 448, 64)      36928     
_________________________________________________________________
block1_pool (MaxPooling2D)   (None, 224, 224, 64)      0         
_________________________________________________________________
block2_conv1 (Conv2D)        (None, 224, 224, 128)     73856     
_________________________________________________________________
block2_conv2 (Conv2D)        (None, 224, 224, 128)     147584    
_________________________________________________________________
block2_pool (MaxPooling2D)   (None, 112, 112, 128)     0     

d+d w/o ft

In [ ]:
one_hot_labels_test = tf.keras.utils.to_categorical(y_test, num_classes=11)
test_loss,test_acc = model.evaluate(X_test,  one_hot_labels_test, verbose=2)

print('\nTest accuracy:', test_acc*100,"%")

In [ ]:
# model_pretrained = tf.keras.applications.InceptionV3(weights="imagenet",include_top=False,input_shape=(rows,cols,3))
# model_pretrained.summary()

# inp = model_pretrained.input
# out = model_pretrained.layers[-2].output

from tensorflow.keras.applications.vgg16 import VGG16
from tensorflow.keras.applications.vgg16 import preprocess_input
import numpy as np
from tensorflow.keras.preprocessing import image
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Dense, GlobalAveragePooling2D
import tensorflow as tf

# create the base pre-trained model
model_pretrained = VGG16(weights='imagenet', include_top=False,input_shape=(rows,cols,3))
model_pretrained.summary()

# first: train only the top layers (which were randomly initialized)
# i.e. freeze all convolutional InceptionV3 layers except the last dense 
# layer for 11 classes that was just added.
for layer in model_pretrained.layers[:15]:
    layer.trainable = False
for layer in model_pretrained.layers[15:]:
    layer.trainable = True
numClasses=11

x = model_pretrained.get_layer(index=-2).output
x_5 = model_pretrained.get_layer(index=-5).output
added_layer = tf.einsum('ijkm,ijkn->imn',x,x)
x = tf.reshape(added_layer,[-1,512*512])
print('Shape of phi_I after reshape', x.get_shape())

x = tf.divide(x,(784.0))  
print('Shape of phi_I after division', x.get_shape())

a = tf.multiply(tf.sign(x),tf.sqrt(tf.abs(x)+1e-12))
print('Shape of y_ssqrt', a.get_shape())

z = tf.nn.l2_normalize(a, dim=1)
print('Shape of z_l2', z.get_shape())


# x = GlobalAveragePooling2D()(x)
# let's add a fully-connected layer
# x = Dense(1024, activation='relu')(x)
# x = Dense(1024, activation='relu')(x)

# and a logistic layer -- let's say we have 24 classes
predictions = Dense(numClasses, activation='softmax')(z)



# this is the model we will train
model = Model(inputs=model_pretrained.input, outputs=predictions)

# compile the model (should be done *after* setting layers to non-trainable)
model.compile(optimizer='rmsprop', loss='categorical_crossentropy',metrics=['accuracy'])
# y_train = np.asarray(y_train).astype('float32').reshape((-1,1))
# y_test = np.asarray(y_test).astype('float32').reshape((-1,1))
one_hot_labels = tf.keras.utils.to_categorical(labels, num_classes=numClasses)
model.summary()
model.fit(x=data,y=one_hot_labels,epochs=10,batch_size=32)



Model: "vgg16"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_4 (InputLayer)         [(None, 448, 448, 3)]     0         
_________________________________________________________________
block1_conv1 (Conv2D)        (None, 448, 448, 64)      1792      
_________________________________________________________________
block1_conv2 (Conv2D)        (None, 448, 448, 64)      36928     
_________________________________________________________________
block1_pool (MaxPooling2D)   (None, 224, 224, 64)      0         
_________________________________________________________________
block2_conv1 (Conv2D)        (None, 224, 224, 128)     73856     
_________________________________________________________________
block2_conv2 (Conv2D)        (None, 224, 224, 128)     147584    
_________________________________________________________________
block2_pool (MaxPooling2D)   (None, 112, 112, 128)     0     

d+d ft

In [ ]:
one_hot_labels_test = tf.keras.utils.to_categorical(y_test, num_classes=11)
test_loss,test_acc = model.evaluate(X_test,  one_hot_labels_test, verbose=2)

print('\nTest accuracy:', test_acc*100,"%")

29/29 - 15s - loss: 4.7513e-04 - accuracy: 1.0000

Test accuracy: 100.0 %


In [ ]:
# model_pretrained = tf.keras.applications.InceptionV3(weights="imagenet",include_top=False,input_shape=(rows,cols,3))
# model_pretrained.summary()

# inp = model_pretrained.input
# out = model_pretrained.layers[-2].output

from tensorflow.keras.applications.inception_v3 import InceptionV3
from tensorflow.keras.preprocessing import image
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Dense, GlobalAveragePooling2D

# create the base pre-trained model
model_pretrained = InceptionV3(weights='imagenet', include_top=False,input_shape=(rows,cols,3))
model_pretrained.summary()
# first: train only the top layers (which were randomly initialized)
# i.e. freeze all convolutional InceptionV3 layers except the last dense 
# layer for 11 classes that was just added.
for layer in model_pretrained.layers:
    layer.trainable = False


x = model_pretrained.get_layer(index=-2).output
x = GlobalAveragePooling2D()(x)
# let's add a fully-connected layer
x = Dense(1024, activation='relu')(x)
# and a logistic layer -- let's say we have 1 classes
predictions = Dense(11, activation='softmax')(x)


# this is the model we will train
model = Model(inputs=model_pretrained.input, outputs=predictions)
for layer in model_pretrained.layers:
    layer.trainable = False

# compile the model (should be done *after* setting layers to non-trainable)
model.compile(optimizer='rmsprop', loss='categorical_crossentropy',metrics=['accuracy'])
# y_train = np.asarray(y_train).astype('float32').reshape((-1,1))
# y_test = np.asarray(y_test).astype('float32').reshape((-1,1))
one_hot_labels = tf.keras.utils.to_categorical(y_train, num_classes=11)
model.summary()
model.fit(x=X_train,
          y=one_hot_labels,
          epochs=15,
          batch_size=32)



Model: "inception_v3"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
input_6 (InputLayer)            [(None, 448, 448, 3) 0                                            
__________________________________________________________________________________________________
conv2d_94 (Conv2D)              (None, 223, 223, 32) 864         input_6[0][0]                    
__________________________________________________________________________________________________
batch_normalization_94 (BatchNo (None, 223, 223, 32) 96          conv2d_94[0][0]                  
__________________________________________________________________________________________________
activation_94 (Activation)      (None, 223, 223, 32) 0           batch_normalization_94[0][0]     
_______________________________________________________________________________________

In [ ]:
# Without fine tuning the accuracy is greater when dataaset is smaller (1100 images)

# at this point, the top layers are well trained and we can start fine-tuning
# convolutional layers from inception V3. We will freeze the bottom N layers
# and train the remaining top layers.

# let's visualize layer names and layer indices to see how many layers
# we should freeze:
for i, layer in enumerate(model_pretrained.layers):
   print(i, layer.name)

# we chose to train the top 2 inception blocks, i.e. we will freeze
# the first 249 layers and unfreeze the rest:
for layer in model.layers[:249]:
   layer.trainable = False
for layer in model.layers[249:]:
   layer.trainable = True

# we need to recompile the model for these modifications to take effect
# we use SGD with a low learning rate
from tensorflow.keras.optimizers import SGD
model.compile(optimizer=SGD(lr=0.0001, momentum=0.9), loss='categorical_crossentropy',metrics=['accuracy'])

# we train our model again (this time fine-tuning the top 2 inception blocks
# alongside the top Dense layers
model.fit(X_train,one_hot_labels,epochs=15,batch_size=32)

0 input_6
1 conv2d_94
2 batch_normalization_94
3 activation_94
4 conv2d_95
5 batch_normalization_95
6 activation_95
7 conv2d_96
8 batch_normalization_96
9 activation_96
10 max_pooling2d_4
11 conv2d_97
12 batch_normalization_97
13 activation_97
14 conv2d_98
15 batch_normalization_98
16 activation_98
17 max_pooling2d_5
18 conv2d_102
19 batch_normalization_102
20 activation_102
21 conv2d_100
22 conv2d_103
23 batch_normalization_100
24 batch_normalization_103
25 activation_100
26 activation_103
27 average_pooling2d_9
28 conv2d_99
29 conv2d_101
30 conv2d_104
31 conv2d_105
32 batch_normalization_99
33 batch_normalization_101
34 batch_normalization_104
35 batch_normalization_105
36 activation_99
37 activation_101
38 activation_104
39 activation_105
40 mixed0
41 conv2d_109
42 batch_normalization_109
43 activation_109
44 conv2d_107
45 conv2d_110
46 batch_normalization_107
47 batch_normalization_110
48 activation_107
49 activation_110
50 average_pooling2d_10
51 conv2d_106
52 conv2d_108
53 conv2d

/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/optimizer_v2/optimizer_v2.py:375: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  "The `lr` argument is deprecated, use `learning_rate` instead.")


Epoch 1/15
107/107 [==============================] - 33s 280ms/step - loss: 0.2429 - accuracy: 0.9500
Epoch 2/15
107/107 [==============================] - 28s 262ms/step - loss: 0.2326 - accuracy: 0.9515
Epoch 3/15
107/107 [==============================] - 28s 260ms/step - loss: 0.2395 - accuracy: 0.9509
Epoch 4/15
107/107 [==============================] - 29s 268ms/step - loss: 0.2196 - accuracy: 0.9567
Epoch 5/15
107/107 [==============================] - 28s 265ms/step - loss: 0.2119 - accuracy: 0.9596
Epoch 6/15
107/107 [==============================] - 28s 263ms/step - loss: 0.2158 - accuracy: 0.9544
Epoch 7/15
107/107 [==============================] - 28s 264ms/step - loss: 0.2055 - accuracy: 0.9585
Epoch 8/15
107/107 [==============================] - 28s 264ms/step - loss: 0.2010 - accuracy: 0.9629
Epoch 9/15
107/107 [==============================] - 28s 264ms/step - loss: 0.1972 - accuracy: 0.9596
Epoch 10/15
107/107 [==============================] - 28s 264ms/step - l

In [ ]:
one_hot_labels_test = tf.keras.utils.to_categorical(y_test, num_classes=11)
test_loss,test_acc = model.evaluate(X_test,  one_hot_labels_test, verbose=2)

print('\nTest accuracy:', test_acc*100,"%")

38/38 - 9s - loss: 1.4082 - accuracy: 0.6136

Test accuracy: 61.36363744735718 %


VGG - 16

In [ ]:
fabric = glob.glob('/content/drive/MyDrive/PS I G3/Dataset/FMD/image/fabric/*.jpg')
foliage = glob.glob('/content/drive/MyDrive/PS I G3/Dataset/FMD/image/foliage/*.jpg')
glass = glob.glob('/content/drive/MyDrive/PS I G3/Dataset/FMD/image/glass/*.jpg')
leather = glob.glob('/content/drive/MyDrive/PS I G3/Dataset/FMD/image/leather/*.jpg')
metal = glob.glob('/content/drive/MyDrive/PS I G3/Dataset/FMD/image/metal/*.jpg')
paper = glob.glob('/content/drive/MyDrive/PS I G3/Dataset/FMD/image/paper/*.jpg')
plastic = glob.glob('/content/drive/MyDrive/PS I G3/Dataset/FMD/image/plastic/*.jpg')
stone = glob.glob('/content/drive/MyDrive/PS I G3/Dataset/FMD/image/stone/*.jpg')
water = glob.glob('/content/drive/MyDrive/PS I G3/Dataset/FMD/image/water/*.jpg')
wood = glob.glob('/content/drive/MyDrive/PS I G3/Dataset/FMD/image/wood/*.jpg')
# # wool = glob.glob('/content/drive/MyDrive/PS I G3/Dataset/FMD/image/wool/*.*')



data = []
labels = []
j= 0
for i in fabric:
    # if j>100:
    #     break
    image=tf.keras.preprocessing.image.load_img(i, color_mode="rgb", target_size= (200,200))
    image=np.array(image)
    data.append(image)
    labels.append(0)
    j +=1
for i in foliage:
    # if j>200:
    #     break
    image=tf.keras.preprocessing.image.load_img(i, color_mode="rgb", target_size= (200,200))
    image=np.array(image)
    data.append(image)
    labels.append(1)
    j +=1
for i in glass:
    # if j>300:
    #     break
    image=tf.keras.preprocessing.image.load_img(i, color_mode="rgb", target_size= (200,200))
    image=np.array(image)
    data.append(image)
    labels.append(2)
    j +=1
for i in leather:
    # if j>400:
    #     break
    image=tf.keras.preprocessing.image.load_img(i, color_mode="rgb", target_size= (200,200))
    image=np.array(image)
    data.append(image)
    labels.append(3)
    j+=1
for i in metal:
    # if j>500 :
    #     break
    image=tf.keras.preprocessing.image.load_img(i, color_mode="rgb", target_size= (200,200))
    image=np.array(image)
    data.append(image)
    labels.append(4)
    j+=1
for i in paper:
    # if j> 600:
    #     break
    image=tf.keras.preprocessing.image.load_img(i, color_mode="rgb", target_size= (200,200))
    image=np.array(image)
    data.append(image)
    labels.append(5)
    j+=1
for i in plastic:
    # if j> 700:
    #     break
    image=tf.keras.preprocessing.image.load_img(i, color_mode="rgb", target_size= (200,200))
    image=np.array(image)
    data.append(image)
    labels.append(6)
    j+=1
for i in stone:
    # if j> 800:
    #     break
    image=tf.keras.preprocessing.image.load_img(i, color_mode="rgb", target_size= (200,200))
    image=np.array(image)
    data.append(image)
    labels.append(7)
    j+=1
for i in water:
    # if j> 900:
    #     break
    image=tf.keras.preprocessing.image.load_img(i, color_mode="rgb", target_size= (200,200))
    image=np.array(image)
    data.append(image)
    labels.append(8)
    j+=1
for i in wood:
    # if j> 1000:
    #     break
    image=tf.keras.preprocessing.image.load_img(i, color_mode="rgb", target_size= (200,200))
    image=np.array(image)
    data.append(image)
    labels.append(9)
    j+=1
print('total images = ',j)
data = np.array(data)
labels = np.array(labels)
# /content/drive/MyDrive/PS I G3/Dataset/FMD/image/fabric/fabric_moderate_001_new.jpg

total images =  1000


In [ ]:
X_train, X_test, y_train, y_test = train_test_split(data, labels, test_size=0.2, random_state=42)

In [11]:
# rows,cols,channels = np.shape(data[0])
rows,cols,channels = (200 ,200 ,3)
print('rows,cols,channels = ',rows,cols,channels)

rows,cols,channels =  200 200 3


In [12]:
# model_pretrained = tf.keras.applications.InceptionV3(weights="imagenet",include_top=False,input_shape=(rows,cols,3))
# model_pretrained.summary()

# inp = model_pretrained.input
# out = model_pretrained.layers[-2].output

from tensorflow.keras.applications.vgg16 import VGG16
from tensorflow.keras.applications.vgg16 import preprocess_input
import numpy as np
from tensorflow.keras.preprocessing import image
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Dense, GlobalAveragePooling2D
import tensorflow as tf

# create the base pre-trained model
model_pretrained = VGG16(weights='imagenet', include_top=False,input_shape=(rows,cols,3))
model_pretrained.summary()

# first: train only the top layers (which were randomly initialized)
# i.e. freeze all convolutional InceptionV3 layers except the last dense 
# layer for 11 classes that was just added.
for layer in model_pretrained.layers[:15]:
    layer.trainable = False
for layer in model_pretrained.layers[15:]:
    layer.trainable = True
numClasses=10

x = model_pretrained.get_layer(index=-2).output
x_5 = model_pretrained.get_layer(index=-5).output
added_layer = tf.einsum('ijkm,ijkn->imn',x,x_5)
x = tf.reshape(added_layer,[-1,512*512])
print('Shape of phi_I after reshape', x.get_shape())

x = tf.divide(x,(784.0))  
print('Shape of phi_I after division', x.get_shape())

a = tf.multiply(tf.sign(x),tf.sqrt(tf.abs(x)+1e-12))
print('Shape of y_ssqrt', a.get_shape())

z = tf.nn.l2_normalize(a, dim=1)
print('Shape of z_l2', z.get_shape())


# x = GlobalAveragePooling2D()(x)
# let's add a fully-connected layer
# x = Dense(1024, activation='relu')(x)
# x = Dense(1024, activation='relu')(x)

# and a logistic layer -- let's say we have 24 classes
predictions = Dense(numClasses, activation='softmax')(z)



# this is the model we will train
model = Model(inputs=model_pretrained.input, outputs=predictions)

# # compile the model (should be done *after* setting layers to non-trainable)
# model.compile(optimizer='rmsprop', loss='categorical_crossentropy',metrics=['accuracy'])
# # y_train = np.asarray(y_train).astype('float32').reshape((-1,1))
# # y_test = np.asarray(y_test).astype('float32').reshape((-1,1))
# one_hot_labels = tf.keras.utils.to_categorical(y_train, num_classes=numClasses)
model.summary()
# model.fit(x=X_train,y=one_hot_labels,epochs=25,batch_size=32)



58892288/58889256 [==============================] - 1s 0us/step
Model: "vgg16"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_1 (InputLayer)         [(None, 200, 200, 3)]     0         
_________________________________________________________________
block1_conv1 (Conv2D)        (None, 200, 200, 64)      1792      
_________________________________________________________________
block1_conv2 (Conv2D)        (None, 200, 200, 64)      36928     
_________________________________________________________________
block1_pool (MaxPooling2D)   (None, 100, 100, 64)      0         
_________________________________________________________________
block2_conv1 (Conv2D)        (None, 100, 100, 128)     73856     
_________________________________________________________________
block2_conv2 (Conv2D)        (None, 100, 100, 128)     147584    
______________________________________________________________

In [ ]:
one_hot_labels_test = tf.keras.utils.to_categorical(y_test, num_classes=10)
test_loss,test_acc = model.evaluate(X_test,  one_hot_labels_test, verbose=2)


print('\nTest accuracy:', test_acc*100,"%")

7/7 - 1s - loss: 0.7884 - accuracy: 0.7050

Test accuracy: 70.49999833106995 %


In [ ]:
import tensorflow as tf


s = tf.random.normal(shape=[7,5,3])
t = tf.random.normal(shape=[7,3,2])
print('s = ',s)
print('t = ',t)
e = tf.einsum('bij,bjk->bik', s, t)
# output[a,i,k] = sum_j s[a,i,j] * t[a, j, k]
print(e.shape)
print('\n\n\n')
print('e = ',e)


s =  tf.Tensor(
[[[-0.8885769   2.5384405   0.23969911]
  [-1.7649558   0.08360087  0.67811894]
  [ 1.8657148  -0.28300974 -0.4434433 ]
  [ 2.7645454   0.0092507  -1.1610818 ]
  [-1.9171015   0.17691602 -1.3639338 ]]

 [[ 0.6148482  -1.6329423   3.0272295 ]
  [ 0.79936486  0.73476535 -1.2748471 ]
  [-0.49792123 -0.6457026   0.7210017 ]
  [-1.0581118  -0.06922852  0.06995879]
  [-0.09803539 -1.5112678  -0.3721594 ]]

 [[-1.8776461  -0.28279606 -2.2707477 ]
  [ 1.4497488  -1.7637967  -0.53261054]
  [-0.84158057  2.177204   -0.679923  ]
  [-0.7900678  -0.31710383 -0.0688142 ]
  [ 0.36276257  1.3644483  -1.2189689 ]]

 [[-0.5528683  -0.69276416 -0.2755585 ]
  [-0.09079573 -0.06009594 -1.3207113 ]
  [-0.27798453  0.02309633  0.75760263]
  [-0.67462355  0.9196274   1.7465358 ]
  [ 0.83056706  0.7889803   0.29458657]]

 [[-1.2456089  -1.4239957   0.9191284 ]
  [-0.18239377  1.0089998   0.42429158]
  [ 0.67865574  0.04365281  0.69633955]
  [-0.38447028  0.0777797   0.08426172]
  [-0.65138185 -